/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TeacherUI;

/**
 *
 * @author User
 */
public class CourseInfo extends javax.swing.JPanel {

    /**
     * Creates new form CourseInfo
     */
    public CourseInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentDataTable = new javax.swing.JTable();

        studentDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Code", "Course Name", "Student Name", "Student ID", "Grade", "Status", "teacherid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentDataTable);
        if (studentDataTable.getColumnModel().getColumnCount() > 0) {
            studentDataTable.getColumnModel().getColumn(0).setResizable(false);
            studentDataTable.getColumnModel().getColumn(1).setResizable(false);
            studentDataTable.getColumnModel().getColumn(2).setResizable(false);
            studentDataTable.getColumnModel().getColumn(3).setResizable(false);
            studentDataTable.getColumnModel().getColumn(4).setResizable(false);
            studentDataTable.getColumnModel().getColumn(5).setResizable(false);
            studentDataTable.getColumnModel().getColumn(6).setMinWidth(0);
            studentDataTable.getColumnModel().getColumn(6).setPreferredWidth(0);
            studentDataTable.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentDataTable;
    // End of variables declaration//GEN-END:variables
}
