/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TeacherUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


/**
 *
 * @author User
 */
public class teacherStudent extends javax.swing.JPanel {

    private CourseBox courseContainer;
    public teacherStudent() {
        initComponents();
        initializeCourseContainer();
    }
    private void initializeCourseContainer() {
        // Create a panel to hold CourseBox panels
        courseContainer = new CourseBox();
        courseContainer.setLayout(new BoxLayout(courseContainer, BoxLayout.Y_AXIS)); // Vertical stacking
        courseContainer.setBackground(Color.WHITE);                  

        // Add the container to the main layout
        JScrollPane scrollPane = new JScrollPane(courseContainer);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);
    }
   public void addCourseBox(String courseCode, String courseName) {
    // Create a new CourseBox instance
    CourseBox courseBox = new CourseBox();

    // Set the course code and course name
    courseBox.courseCode.setText(courseCode);
    courseBox.courseName.setText(courseName);

    // Add the CourseBox to the container panel
    courseContainer.add(courseBox);

    // Refresh the UI
    courseContainer.revalidate();
    courseContainer.repaint();
}

    public void removeCourseBox(String courseCodeText) {
    Component[] components = courseContainer.getComponents();
    for (Component component : components) {
        if (component instanceof CourseBox) {
            CourseBox courseBox = (CourseBox) component;

            // Check if this is the CourseBox to remove using the public JLabel
            if (courseBox.courseCode.getText().equals(courseCodeText)) {
                courseContainer.remove(courseBox); // Remove the CourseBox
                break;
            }
        }
    }

    // Refresh the UI
    courseContainer.revalidate();
    courseContainer.repaint();
}

public void updateCourseBox(String courseCodeText, String newCourseName) {
    Component[] components = courseContainer.getComponents();
    for (Component component : components) {
        if (component instanceof CourseBox) {
            CourseBox courseBox = (CourseBox) component;

            // Check if this is the CourseBox to update using the public JLabel
            if (courseBox.courseCode.getText().equals(courseCodeText)) {
                // Update the courseName JLabel
                courseBox.courseName.setText(newCourseName);
                break;
            }
        }
    }

    // Refresh the UI
    courseContainer.revalidate();
    courseContainer.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
