package Admin;

import static Data.Controller.PopulateTable.populateTeacherTable;
import Data.Database.DatabaseConnection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class VerifyTeacher extends javax.swing.JPanel {

   
    private DefaultTableModel teacherReqTableModel;
    public VerifyTeacher() {
        initComponents();
        teacherReqTableModel = (DefaultTableModel) teacherReqTable.getModel();
        populateTeacherTable( teacherReqTable);
    }
    public void TextFieldEmpty(){
        fullName.setText("");
        program.setText("");
        status.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        teacherReqTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        fullName = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        declineBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        teacherReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Program", "Role", "Status", "teacher ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacherReqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherReqTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacherReqTable);
        if (teacherReqTable.getColumnModel().getColumnCount() > 0) {
            teacherReqTable.getColumnModel().getColumn(0).setResizable(false);
            teacherReqTable.getColumnModel().getColumn(1).setResizable(false);
            teacherReqTable.getColumnModel().getColumn(2).setMinWidth(0);
            teacherReqTable.getColumnModel().getColumn(2).setPreferredWidth(0);
            teacherReqTable.getColumnModel().getColumn(2).setMaxWidth(0);
            teacherReqTable.getColumnModel().getColumn(3).setResizable(false);
            teacherReqTable.getColumnModel().getColumn(4).setMinWidth(0);
            teacherReqTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            teacherReqTable.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        fullName.setBackground(new java.awt.Color(255, 255, 255));
        fullName.setOpaque(true);

        status.setBackground(new java.awt.Color(255, 255, 255));
        status.setOpaque(true);

        program.setBackground(new java.awt.Color(255, 255, 255));
        program.setOpaque(true);

        jLabel4.setText("Name");

        jLabel5.setText("Program");

        jLabel6.setText("Status");

        declineBtn.setText("Decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(176, 176, 176))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teacherReqTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherReqTableMouseClicked
        // TODO add your handling code here:
        int selectIndex = teacherReqTable.getSelectedRow();
        fullName.setText(teacherReqTableModel.getValueAt(selectIndex, 0).toString());
        program.setText(teacherReqTableModel.getValueAt(selectIndex, 1).toString());
        status.setText(teacherReqTableModel.getValueAt(selectIndex, 3).toString());
    }//GEN-LAST:event_teacherReqTableMouseClicked

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = teacherReqTable.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a teacher to confirm.", "No Selection", JOptionPane.WARNING_MESSAGE);
    return;
}

try {
    // Extract student details from the selected row
    String fullName = teacherReqTableModel.getValueAt(selectedRow, 0).toString();
    String program = teacherReqTableModel.getValueAt(selectedRow, 1).toString();

    // Prepare the SQL statement for updating the status
    String sql = "UPDATE facultyuser SET status = 'verified' WHERE fullname = ? AND program = ?";

    // Use the singleton instance of DatabaseConnection
    DatabaseConnection dbConnection = DatabaseConnection.getInstance();
    try (PreparedStatement pstmt = dbConnection.getConnection().prepareStatement(sql)) {
        // Set parameters for the query
        pstmt.setString(1, fullName);
        pstmt.setString(2, program);

        // Execute the update
        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            // Update the UI to reflect the changes
            teacherReqTableModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Teacher has been verified successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to verify the teacher. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        TextFieldEmpty();
    }
} catch (Exception ex) {
    // Log the exception and notify the user
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "An error occurred while verifying the teacher.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_confirmBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = teacherReqTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a teacher to decline.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Extract teacher details from the selected row
    String fullName = teacherReqTableModel.getValueAt(selectedRow, 0).toString();
    String program = teacherReqTableModel.getValueAt(selectedRow, 1).toString();

    try {
        // SQL query to delete the teacher from the database
        String sql = "DELETE FROM facultyuser WHERE fullname = ? AND program = ?";

        // Use the singleton instance of DatabaseConnection
        DatabaseConnection dbConnection = DatabaseConnection.getInstance();
        try (PreparedStatement pstmt = dbConnection.getConnection().prepareStatement(sql)) {
            // Set parameters for the query
            pstmt.setString(1, fullName);
            pstmt.setString(2, program);

            // Execute the delete operation
            int rowsDeleted = pstmt.executeUpdate();

            if (rowsDeleted > 0) {
                // Update the UI to remove the row
                teacherReqTableModel.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Teacher request has been declined and removed.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to decline the teacher request. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            TextFieldEmpty();
        }
    } catch (Exception ex) {
        // Log the exception and notify the user
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred while declining the teacher request.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_declineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton declineBtn;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel program;
    private javax.swing.JLabel status;
    private javax.swing.JTable teacherReqTable;
    // End of variables declaration//GEN-END:variables
}
